pipeline {
    agent {
        docker {
            label 'agent'
            image "rebachi/bank-leumi:agent"
            args '-u 0:0 -v /var/run/docker.sock:/var/run/docker.sock'
            alwaysPull true
        }
    }

    environment {
        registry = "rebachi/bank-leumi"
        registryCredential = 'docker-hub-id-new'
    }

    stages {
        stage('Checkout scm') {
            steps {
                sh 'rm -rf bank-leumi'
                checkout scm
                script {
                    sh 'ls -R'
                }
            }
        }

        stage('Parallel Stages For Static Analysis Tests') {
            parallel {
                stage("Pylint") {
                    steps {
                        dir('app') {
                            sh '''
                                export PYTHONPATH=.
                                pylint --output-format=parseable --fail-under=0 app.py
                            '''
                        }
                    }
                }

                stage("Bandit Scan") {
                    steps {
                        dir('app') {
                            sh '''
                                bandit -r . --severity-level high
                            '''
                        }
                    }
                }
            }
        }



        stage("Docker Build") {
            steps {
                dir('app') {
                    script {
                        sh '''
                            docker build -t ${registry}:${env.BUILD_NUMBER} .
                        '''
                    }
                }
            }
        }


        stage("Docker Push") {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        sh "docker push ${registry}:${env.BUILD_NUMBER}"
                    }
                }
            }
        }

        stage("Trigger CD Job") {
            steps {
                script {
                    build job: 'CD',
                        parameters: [
                            string(name: 'DOCKER_IMAGE', value: "${registry}:${env.BUILD_NUMBER}")
                        ]
                }
            }
        }
    }

    post {
        cleanup {
            steps {
                script {
                    sh 'docker rmi ${registry}:${env.BUILD_NUMBER} || true'
                }
            }
        }
    }
}
