pipeline { 
    agent {
        label 'slave'
        image "rebachi/bank-leumi:agent"
        alwaysPull true
    } 

    enviorment {
        registry = "rebachi/bank-leumi"
        registryCredential = 'DOCKER_CREDENTIALS'
    }

    stages {
        stage('Checkout scm') { 
            steps { 
                checkout scm
            }
        }
        stage('Parallel Stages For Static Analysis Tests'){
            parallel {
                stage("Pylint") {
                    steps {
                        sh 'pylint --output-format=parseable --fail-under=5 ./app/app.py'
                    }
                }

                stage("Bandit Scan") {
                    steps {
                        sh 'bandit -r ./app'
                    }
                }
            }
        }

        stage("Docker Build") {
            steps {
                script {
                    app = docker.build("${registry}:${env.BUILD_NUMBER}", "./app")
                }
            }
        }

        stage("Docker Push") {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        app.push("${env.BUILD_NUMBER}")
                    }
                }
            }
        }

        stage("Trigger CD JOb") {
            steps {
                build job: 'CD',
                    parameters: [
                        string(name: 'DOCKER_IMAGE', value: app.imageName())
                    ]
            }
        }
    }
}